version: "3"
services:
  db:
    container_name: example-db
    build: ./database
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rd
      MYSQL_DATABASE: database
    volumes:
      - ./database/db/data:/var/lib/mysql
      - ./database/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 7582:3306

  phpmyadmin:
    container_name: example-admin
    build: ./phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_USER=root
      - PMA_PASSWORD=p@ssw0rd
    ports:
      - 10111:80

  python:
    container_name: web
    build: ./web

    volumes:
      - ./web:/web
    stdin_open: true
    tty: true
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=run.py
