"""empty message

Revision ID: 23c56afe22e1
Revises: 7ea618fbe059
Create Date: 2020-01-13 12:09:48.583991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23c56afe22e1'
down_revision = '7ea618fbe059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unko')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unko',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('kuso', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
